version: "3.8"
services:
  api:
    build:
      context: src/server
      dockerfile: Dockerfile
    container_name: person-name-annotator
    environment:
      - SQL_USER
      - SQL_PASSWORD
      - SQL_HOST
      - SQL_DB
      - SQL_PORT
      - SYNAPSE_USERNAME
      - SYNAPSE_API_KEY
      - DATA_SYNAPSE_ID
      - DATA_MD5
      - GOLDSTANDARD_SYNAPSE_ID
      - GOLDSTANDARD_MD5
    ports:
      - "${SERVER_PORT}:8080"
